# ViPER4AndroidFX
TARGET_INCLUDE_VIPERFX := false

# Lineage SDK
TARGET_DISABLE_LINEAGE_SDK := false

# EPPE
TARGET_DISABLE_EPPE := false

# Bootanimation
TARGET_INCLUDE_BOOT_ANIMATIONS := true
TARGET_SCREEN_WIDTH := 1280
TARGET_SCREEN_HEIGHT := 2772

# Blur
TARGET_ENABLE_BLUR := true

# Gramophone
TARGET_INCLUDE_GRAMOPHONE := false

# Udfps
TARGET_HAS_UDFPS := true

# Targets - true
TARGET_EXCLUDES_AUDIOFX := true
TARGET_SUPPORTS_64_BIT_APPS := true

# Targets - false
TARGET_ENABLE_FP_OVERRIDE := false
TARGET_BUILD_DEVICE_AS_WEBCAM := false

# Other ROM feature flags
PERF_ANIM_OVERRIDE := true
TARGET_ENABLES_IMS_OVERRIDES := true
TORCH_STR_SUPPORTED := true
USE_REALITY_ENGINE := false

# BCR
TARGET_INCLUDE_BCR := true

# GMS
ifeq ($(WITH_GMS),true)
TARGET_USES_MINI_GAPPS := false
TARGET_USES_PICO_GAPPS := false
TARGET_SUPPORTS_QUICK_TAP := true
TARGET_INCLUDE_LIVE_WALLPAPERS := true
TARGET_INCLUDE_STOCK_ARCORE := true
TARGET_SUPPORTS_GOOGLE_RECORDER := true
TARGET_INCLUDE_MOSEY := false
TARGET_USES_MOSEY_NOPAUTH := false
endif

# Bypass Lock State for Fenrir
$(call soong_config_set_bool,fastbootd,bypass_lock_state,true)
